name: CI Pipeline (Lint and Test)

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: 3.13

      - name: Flake8 Linting
        uses: lukacat10/Flake8@v5

  test:
    runs-on: [ubuntu-latest]

    needs: lint

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: 3.13

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Generate new lock file
        run: poetry lock

      - name: Install dependencies
        run: poetry install
      
      - name: Run tests
        run: poetry run pytest -v